### ISSUE TITLE
No module named open3d

### ISSUE THREAD

**Issue by ramyagopinathpsg** [felixchenfy/3D-Scanner-by-Baxter#1]
ImportError: No module named open3d
[calib_camera_pose-2] process has died [pid 8784, exit code 1, cmd /home/div/6D_pose_ws/src/3D-Scanner-by-Baxter/src_main/calib_camera_pose/calib_camera_pose.py __name:=calib_camera_pose __log:=/home/div/.ros/log/c26552a8-bd93-11e9-926e-9c305bc8fc79/calib_camera_pose-2.log].

I have faced this issue. I tried installing pip install open3d-python too.. Also I found that, .log file is not present in .ros file.. Could you plz help me in this

**Comment by felixchenfy** [comment]
@ramyagopinathpsg 
* About open3d, try this: $ pip install --user open3d-python
  See this page: http://www.open3d.org/docs/release/getting_started.html#id2
* About .log, I'm not sure what error you are talking about
